Whatsapp complete functionality
helpbuttons/helpbuttons pull request #1012
Opened 2024-12-11 19:08 UTC by watchoutfreedom

2024-12-17 13:14 UTC, albjeremias requested changes

2024-12-17 13:14 UTC, albjeremias commented on web/src/components/button/CardButton/index.tsx
> +          {/* <ShowPhone user={button.owner} /> */}
remove comments please

2024-12-17 13:14 UTC, albjeremias commented on web/src/components/button/CardButton/index.tsx
> +  // const getPhone = () => {
remove comments

2024-12-17 13:14 UTC, albjeremias commented on web/src/components/map/Map/HexagonExploreMap.tsx
> +            {/* <HbMapOverlay selectedNetwork={selectedNetwork} /> */}
why is this commented now? has nothing to do with this issue

2024-12-18 00:46 UTC, watchoutfreedom commented on web/src/components/map/Map/HexagonExploreMap.tsx
> +            {/* <HbMapOverlay selectedNetwork={selectedNetwork} /> */}
I'm removing it totally, it doesn't make sense in mobile to have more info over the map

2024-12-18 08:41 UTC, watchoutfreedom reviewed
ready

2024-12-26 11:09 UTC, closed without merging